//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlantsEntities : DbContext
    {
        public PlantsEntities()
            : base("name=PlantsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PlantCare> PlantCare { get; set; }
        public virtual DbSet<PlantLighting> PlantLighting { get; set; }
        public virtual DbSet<Plants> Plants { get; set; }
        public virtual DbSet<SprayingPlants> SprayingPlants { get; set; }
        public virtual DbSet<TypePlants> TypePlants { get; set; }
        public virtual DbSet<ViewPlants> ViewPlants { get; set; }
        public virtual DbSet<WateringPlants> WateringPlants { get; set; }
    }
}
