//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plants
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public int IdType { get; set; }
        public int IdCare { get; set; }
        public int IdWatering { get; set; }
        public int IdLighting { get; set; }
        public int IdSpraying { get; set; }
        public int IdSpecies { get; set; }
    
        public virtual PlantCare PlantCare { get; set; }
        public virtual PlantLighting PlantLighting { get; set; }
        public virtual ViewPlants ViewPlants { get; set; }
        public virtual SprayingPlants SprayingPlants { get; set; }
        public virtual TypePlants TypePlants { get; set; }
        public virtual WateringPlants WateringPlants { get; set; }
    }
}
